# Generated by Django 4.2.16 on 2026-06-26 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(default='Community Service Project', max_length=200)),
                ('project_topic', models.TextField(default='Safe Usage of Internet and Cybercrime Awareness in Rural Areas')),
                ('mentor_name', models.CharField(default='Dr. R. Rajender', max_length=200)),
                ('college_name', models.CharField(default='', max_length=300)),
                ('academic_year', models.CharField(default='2024–2025', max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('hero_video', models.FileField(blank=True, null=True, upload_to='site/')),
                ('hero_tagline', models.CharField(default='Bridging the Digital Divide in Rural Communities', max_length=300)),
                ('show_ai_assistant', models.BooleanField(default=True)),
                ('survey_open', models.BooleanField(default=True, help_text='Allow new survey submissions')),
                ('maintenance_mode', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
