# Generated by Django 4.2.16 on 2026-06-26 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('visits', '0001_initial'),
        ('villages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('age_group', models.CharField(choices=[('below_18', 'Below 18 years'), ('18_25', '18–25 years'), ('26_35', '26–35 years'), ('36_45', '36–45 years'), ('46_60', '46–60 years'), ('above_60', 'Above 60 years')], max_length=20)),
                ('education', models.CharField(choices=[('none', 'No formal education'), ('primary', 'Primary (1–5)'), ('upper_primary', 'Upper Primary (6–8)'), ('secondary', 'Secondary (9–10)'), ('intermediate', 'Intermediate / +2'), ('graduate', 'Graduate'), ('postgraduate', 'Postgraduate and above')], max_length=30)),
                ('occupation', models.CharField(choices=[('student', 'Student'), ('farmer', 'Farmer'), ('daily_wage', 'Daily wage worker'), ('private_employee', 'Private employee'), ('government_employee', 'Government employee'), ('self_employed', 'Self-employed / Business'), ('homemaker', 'Homemaker'), ('unemployed', 'Unemployed'), ('other', 'Other')], max_length=30)),
                ('occupation_other', models.CharField(blank=True, max_length=200)),
                ('uses_internet', models.BooleanField(default=False)),
                ('devices', models.JSONField(blank=True, default=list)),
                ('device_other', models.CharField(blank=True, max_length=200)),
                ('connection_type', models.CharField(blank=True, choices=[('mobile_data', 'Mobile data'), ('broadband', 'Home broadband / Wi-Fi'), ('public_wifi', 'Public Wi-Fi'), ('other', 'Other')], max_length=20)),
                ('connection_other', models.CharField(blank=True, max_length=200)),
                ('hours_per_day', models.CharField(blank=True, choices=[('less_1', 'Less than 1 hour'), ('1_2', '1–2 hours'), ('2_4', '2–4 hours'), ('4_6', '4–6 hours'), ('more_6', 'More than 6 hours')], max_length=10)),
                ('internet_purposes', models.JSONField(blank=True, default=list)),
                ('purpose_other', models.CharField(blank=True, max_length=200)),
                ('cyber_awareness_rating', models.CharField(blank=True, choices=[('very_low', 'Very Low'), ('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('very_high', 'Very High')], max_length=10)),
                ('knows_otp_rule', models.CharField(blank=True, choices=[('yes', 'Yes, I know this.'), ('partial', 'I have heard about it but I am not fully sure.'), ('no', 'No, I do not know this.')], max_length=10)),
                ('faced_fraud', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('not_sure', 'Not Sure')], max_length=10)),
                ('fraud_description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('is_imported', models.BooleanField(default=False)),
                ('import_source', models.CharField(blank=True, max_length=200)),
                ('village', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_responses', to='villages.village')),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_responses', to='visits.fieldvisit')),
            ],
            options={
                'verbose_name': 'Survey Response',
                'verbose_name_plural': 'Survey Responses',
                'ordering': ['-created_at'],
            },
        ),
    ]
