# Generated by Django 4.2.16 on 2026-06-26 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('visits', '0001_initial'),
        ('villages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='gallery/%Y/%m/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='gallery/thumbs/%Y/%m/')),
                ('caption', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('survey', 'Survey Activity'), ('awareness', 'Awareness Session'), ('village', 'Village Life'), ('team', 'Team Photo'), ('infrastructure', 'Infrastructure'), ('event', 'Event'), ('before_after', 'Before vs After'), ('other', 'Other')], default='other', max_length=30)),
                ('date_taken', models.DateField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='Bytes', null=True)),
                ('exif_data', models.JSONField(blank=True, null=True)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=500)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('before_after_pair', models.ForeignKey(blank=True, help_text="Link to 'before' photo for comparison", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='after_photos', to='gallery.photo')),
                ('village', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='villages.village')),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='visits.fieldvisit')),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
                'ordering': ['-date_taken', '-created_at'],
            },
        ),
    ]
