# Generated by Django 4.2.16 on 2026-06-26 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('history', models.TextField(blank=True)),
                ('population', models.PositiveIntegerField(blank=True, null=True)),
                ('households', models.PositiveIntegerField(blank=True, null=True)),
                ('area_sqkm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='villages/heroes/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='villages/thumbnails/')),
                ('nearby_landmarks', models.TextField(blank=True, help_text='Comma-separated landmarks')),
                ('primary_occupation', models.CharField(blank=True, max_length=200)),
                ('internet_infrastructure', models.TextField(blank=True)),
                ('challenges', models.TextField(blank=True)),
                ('community_response', models.TextField(blank=True)),
                ('color_accent', models.CharField(default='#06B6D4', help_text='Hex color for village card accent', max_length=7)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Village',
                'verbose_name_plural': 'Villages',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VillageObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('observation_date', models.DateField(blank=True, null=True)),
                ('category', models.CharField(blank=True, choices=[('infrastructure', 'Infrastructure'), ('awareness', 'Awareness'), ('challenge', 'Challenge'), ('positive', 'Positive Finding'), ('recommendation', 'Recommendation')], max_length=100)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='villages.village')),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
