# Generated by Django 4.2.16 on 2026-06-26 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='village',
            name='district',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='village',
            name='state',
            field=models.CharField(blank=True, default='Andhra Pradesh', max_length=200),
        ),
    ]
