# Generated by Django 4.2.16 on 2026-06-26 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('villages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day_number', models.PositiveIntegerField(help_text='Day 1, Day 2, …', unique=True)),
                ('title', models.CharField(max_length=300)),
                ('date', models.DateField()),
                ('summary', models.TextField()),
                ('objectives', models.JSONField(blank=True, default=list)),
                ('activities', models.JSONField(blank=True, default=list)),
                ('attendance', models.PositiveIntegerField(default=0)),
                ('surveys_collected', models.PositiveIntegerField(default=0)),
                ('observations', models.TextField(blank=True)),
                ('problems_faced', models.TextField(blank=True)),
                ('solutions', models.TextField(blank=True)),
                ('lessons_learned', models.TextField(blank=True)),
                ('impact', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('village', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='villages.village')),
            ],
            options={
                'verbose_name': 'Field Visit',
                'verbose_name_plural': 'Field Visits',
                'ordering': ['day_number'],
            },
        ),
        migrations.CreateModel(
            name='VisitMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video'), ('document', 'Document')], default='photo', max_length=20)),
                ('file', models.FileField(upload_to='visits/media/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=500)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='visits.fieldvisit')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
